In [1]:
# Importando as bibliotecas
import pandas as pd
import tensorflow as tf
import sklearn

In [2]:
pd.__version__, tf.__version__, sklearn.__version__

('2.2.2', '2.20.0', '1.6.1')

In [3]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [4]:
base = pd.read_csv('/content/autos.csv', encoding = 'ISO-8859-1')
base

,dateCrawled,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage,dateCreated,nrOfPictures,postalCode,lastSeen
0,2016-03-24 11:52:17,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN,2016-03-24 00:00:00,0,70435,2016-04-07 03:16:57
1,2016-03-24 10:58:45,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja,2016-03-24 00:00:00,0,66954,2016-04-07 01:46:50
2,2016-03-14 12:52:21,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN,2016-03-14 00:00:00,0,90480,2016-04-05 12:47:46
3,2016-03-17 16:54:04,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein,2016-03-17 00:00:00,0,91074,2016-03-17 17:40:17
4,2016-03-31 17:25:20,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein,2016-03-31 00:00:00,0,60437,2016-04-06 10:17:21
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,2016-03-14 17:48:27,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN,2016-03-14 00:00:00,0,39576,2016-04-06 00:46:52
371524,2016-03-05 19:56:21,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein,2016-03-05 00:00:00,0,26135,2016-03-11 18:17:12
371525,2016-03-19 18:57:12,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein,2016-03-19 00:00:00,0,87439,2016-04-07 07:15:26
371526,2016-03-20 19:41:08,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN,2016-03-20 00:00:00,0,40764,2016-03-24 12:45:21
371527,2016-03-07 19:39:19,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein,2016-03-07 00:00:00,0,73326,2016-03-22 03:17:10

In [5]:
base = base.drop('dateCrawled', axis = 1) # apagar as colunas especificas de 20 para 15
base = base.drop('dateCreated', axis = 1)
base = base.drop('nrOfPictures', axis = 1)
base = base.drop('postalCode', axis = 1)
base = base.drop('lastSeen', axis = 1)
base

,name,seller,offerType,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,Golf_3_1.6,privat,Angebot,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
1,A5_Sportback_2.7_Tdi,privat,Angebot,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
2,"Jeep_Grand_Cherokee_""Overland""",privat,Angebot,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN
3,GOLF_4_1_4__3TÜRER,privat,Angebot,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein
4,Skoda_Fabia_1.4_TDI_PD_Classic,privat,Angebot,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
371523,Suche_t4___vito_ab_6_sitze,privat,Angebot,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN
371524,Smart_smart_leistungssteigerung_100ps,privat,Angebot,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein
371525,Volkswagen_Multivan_T4_TDI_7DC_UY2,privat,Angebot,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein
371526,VW_Golf_Kombi_1_9l_TDI,privat,Angebot,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN
371527,BMW_M135i_vollausgestattet_NP_52.720____Euro,privat,Angebot,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein

In [6]:
base['name'].value_counts() # quantidades de registros da coluna name

name
Ford_Fiesta                                                         657
BMW_318i                                                            627
Opel_Corsa                                                          622
Volkswagen_Golf_1.4                                                 603
BMW_316i                                                            523
                                                                   ...
Subaru_Justy_1.3                                                      1
OPEL_CORSA_B__ECO_SWING__TÜV_1/17_8fach_Bereifung/Schiebedach/CD      1
Ford_C___Max_Titanium_1_0_L_EcoBoost                                  1
VW_Derby_Bj_80__Scheunenfund                                          1
BMW_316i___e36_Limousine___Bastlerfahrzeug__Export                    1
Name: count, Length: 233531, dtype: int64

In [7]:
base = base.drop('name', axis = 1) # apagar a coluna name

In [8]:
base['seller'].value_counts() # quantidades de registros da coluna seller

seller
privat        371525
gewerblich         3
Name: count, dtype: int64

In [9]:
base = base.drop('seller', axis = 1)

In [10]:
base['offerType'].value_counts()

offerType
Angebot    371516
Gesuch         12
Name: count, dtype: int64

In [11]:
base = base.drop('offerType', axis = 1)

In [12]:
base # agora está com 12 colunas

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
1,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN
3,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein
4,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN
371524,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein
371525,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein
371526,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN
371527,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein

In [13]:
base.loc[base['price'] <= 10] # localizar a tabela price menor ou igual a 10

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
7,0,test,limousine,1980,manuell,50,andere,40000,7,benzin,volkswagen,nein
40,0,test,NaN,1990,NaN,0,corsa,150000,1,benzin,opel,NaN
60,1,control,suv,1994,manuell,286,NaN,150000,11,NaN,sonstige_autos,NaN
91,1,control,limousine,1995,manuell,113,e_klasse,150000,4,diesel,mercedes_benz,nein
115,0,test,NaN,2017,manuell,0,golf,5000,12,benzin,volkswagen,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371356,0,control,NaN,2000,manuell,65,corsa,150000,0,NaN,opel,ja
371392,0,test,kleinwagen,2002,manuell,60,fiesta,150000,3,benzin,ford,NaN
371402,0,control,kleinwagen,1999,manuell,53,swift,150000,3,benzin,suzuki,NaN
371431,0,control,kleinwagen,1999,manuell,37,arosa,150000,7,benzin,seat,ja
371522,0,control,NaN,2005,manuell,0,colt,150000,7,benzin,mitsubishi,ja

In [14]:
base['price'].mean() # media do preco medio

np.float64(17295.14186548524)

In [15]:
base = base[base['price'] > 10] # recriando a variavel com novo filtro (>10)

In [16]:
base.shape

(359410, 12)

In [17]:
base.loc[base['price'] > 350000]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
1846,579000,control,coupe,1980,manuell,277,andere,20000,12,benzin,bmw,nein
10649,420000,control,coupe,2004,manuell,483,911,50000,4,benzin,porsche,nein
14663,11111111,control,coupe,2003,manuell,64,polo,150000,2,benzin,volkswagen,NaN
16889,1000000,control,kombi,1998,NaN,0,mondeo,150000,0,benzin,ford,ja
20143,1250000,test,coupe,2016,manuell,500,911,5000,3,benzin,porsche,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
364171,3890000,test,coupe,2006,NaN,799,NaN,5000,7,NaN,sonstige_autos,nein
365461,599000,control,coupe,1980,manuell,377,andere,5000,3,benzin,bmw,nein
366653,99999999,control,cabrio,1996,manuell,192,3er,150000,0,NaN,bmw,NaN
366861,3895000,test,coupe,2006,NaN,799,NaN,5000,4,benzin,sonstige_autos,nein
367041,1600000,test,coupe,2005,NaN,625,NaN,10000,4,benzin,sonstige_autos,nein

In [18]:
base = base.loc[base['price'] < 350000]

In [19]:
base.shape

(359291, 12)

In [20]:
base.loc[pd.isnull(base['vehicleType'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
16,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN
22,2900,test,NaN,2018,manuell,90,meriva,150000,5,benzin,opel,nein
26,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein
31,899,control,NaN,2016,manuell,60,clio,150000,6,benzin,renault,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371504,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371519,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [21]:
base['vehicleType'].value_counts() # quantidade

vehicleType
limousine     93614
kleinwagen    78014
kombi         65921
bus           29699
cabrio        22509
coupe         18386
suv           14477
andere         3125
Name: count, dtype: int64

In [22]:
base['vehicleType'].mode() # moda

0    limousine
Name: vehicleType, dtype: object

In [23]:
base.loc[pd.isnull(base['gearbox'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
15,450,test,kleinwagen,1910,NaN,0,ka,5000,0,benzin,ford,NaN
16,300,test,NaN,2016,NaN,60,polo,150000,0,benzin,volkswagen,NaN
32,245,test,limousine,1994,NaN,0,golf,150000,2,benzin,volkswagen,nein
37,1500,test,NaN,2016,NaN,0,kangoo,150000,1,diesel,renault,nein
70,1200,test,coupe,2001,NaN,0,astra,150000,0,NaN,opel,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371443,3300,control,kombi,2006,NaN,0,touran,150000,7,diesel,volkswagen,NaN
371460,3500,control,NaN,1995,NaN,0,polo,150000,0,NaN,volkswagen,NaN
371486,350,control,kleinwagen,1996,NaN,65,punto,150000,0,NaN,fiat,NaN
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [24]:
base['gearbox'].value_counts()

gearbox
manuell      266547
automatik     75508
Name: count, dtype: int64

In [25]:
base.loc[pd.isnull(base['model'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
1,18300,test,coupe,2011,manuell,190,NaN,125000,5,diesel,audi,ja
83,350,control,kleinwagen,1997,manuell,54,NaN,150000,3,NaN,fiat,ja
139,1450,control,limousine,1992,manuell,136,NaN,150000,0,NaN,audi,nein
156,6799,control,kleinwagen,2009,NaN,60,NaN,20000,5,benzin,volkswagen,nein
165,500,control,kleinwagen,1999,manuell,0,NaN,150000,0,benzin,renault,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
371399,560,control,kleinwagen,2001,automatik,170,NaN,90000,0,benzin,fiat,ja
371476,9400,control,kombi,2007,manuell,200,NaN,150000,4,diesel,sonstige_autos,ja
371495,180,control,NaN,1995,NaN,0,NaN,125000,3,benzin,opel,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [26]:
base['model'].value_counts()

model
golf               28989
andere             25560
3er                19905
polo               12604
corsa              12149
                   ...
serie_2                8
rangerover             6
serie_3                3
serie_1                1
discovery_sport        1
Name: count, Length: 251, dtype: int64

In [27]:
base.loc[pd.isnull(base['fuelType'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
9,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN
13,2500,control,kombi,2004,manuell,131,passat,150000,2,NaN,volkswagen,nein
26,5555,control,NaN,2017,manuell,125,c4,125000,4,NaN,citroen,nein
36,1600,control,andere,1991,manuell,75,kadett,70000,0,NaN,opel,NaN
41,7500,control,limousine,2002,automatik,306,e_klasse,150000,4,NaN,mercedes_benz,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371496,3850,test,cabrio,2006,manuell,108,2_reihe,125000,2,NaN,peugeot,nein
371504,2600,control,NaN,2005,automatik,0,c_klasse,150000,9,NaN,mercedes_benz,NaN
371509,1900,test,NaN,2000,manuell,110,NaN,150000,7,NaN,volkswagen,nein
371519,5250,control,NaN,2016,automatik,150,159,150000,12,NaN,alfa_romeo,nein
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN

In [28]:
base['fuelType'].value_counts()

fuelType
benzin     217582
diesel     106002
lpg          5222
cng           557
hybrid        271
andere        165
elektro       101
Name: count, dtype: int64

In [29]:
base.loc[pd.isnull(base['notRepairedDamage'])]

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,NaN,1993,manuell,0,golf,150000,0,benzin,volkswagen,NaN
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,NaN
8,14500,control,bus,2014,manuell,125,c_max,30000,8,benzin,ford,NaN
9,999,test,kleinwagen,1998,manuell,101,golf,150000,0,NaN,volkswagen,NaN
12,999,control,kombi,1995,manuell,115,passat,150000,11,benzin,volkswagen,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
371507,5999,test,kombi,2005,manuell,140,a4,150000,4,diesel,audi,NaN
371514,999,control,cabrio,2000,manuell,95,megane,150000,4,benzin,renault,NaN
371515,1690,test,kombi,2004,manuell,55,fabia,150000,4,benzin,skoda,NaN
371523,2200,test,NaN,2005,NaN,0,NaN,20000,1,NaN,sonstige_autos,NaN
371526,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,NaN

In [30]:
base['notRepairedDamage'].value_counts()

notRepairedDamage
nein    259301
ja       34004
Name: count, dtype: int64

In [31]:
valores = {'vehicleType' : 'limousine',
           'gearbox' : 'manuell',
           'model' : 'golf',
           'fuelType' : 'benzin',
           'notRepairedDamage' : 'nein'}

In [32]:
base = base.fillna(value = valores) # Quando for encontrado um valor nulo será preenchido por um dos valores acima

In [33]:
base

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,limousine,1993,manuell,0,golf,150000,0,benzin,volkswagen,nein
1,18300,test,coupe,2011,manuell,190,golf,125000,5,diesel,audi,ja
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,nein
3,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein
4,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
371523,2200,test,limousine,2005,manuell,0,golf,20000,1,benzin,sonstige_autos,nein
371524,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein
371525,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein
371526,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,nein
371527,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein

In [34]:
base.isnull().sum() # verificar se tem valor nulo ainda

price                  0
abtest                 0
vehicleType            0
yearOfRegistration     0
gearbox                0
powerPS                0
model                  0
kilometer              0
monthOfRegistration    0
fuelType               0
brand                  0
notRepairedDamage      0
dtype: int64

In [35]:
base.columns # ordem das colunas

Index(['price', 'abtest', 'vehicleType', 'yearOfRegistration', 'gearbox',
       'powerPS', 'model', 'kilometer', 'monthOfRegistration', 'fuelType',
       'brand', 'notRepairedDamage'],
      dtype='object')

In [36]:
X = base.iloc[:, 1:12].values
X

array([['test', 'limousine', 1993, ..., 'benzin', 'volkswagen', 'nein'],
       ['test', 'coupe', 2011, ..., 'diesel', 'audi', 'ja'],
       ['test', 'suv', 2004, ..., 'diesel', 'jeep', 'nein'],
       ...,
       ['test', 'bus', 1996, ..., 'diesel', 'volkswagen', 'nein'],
       ['test', 'kombi', 2002, ..., 'diesel', 'volkswagen', 'nein'],
       ['control', 'limousine', 2013, ..., 'benzin', 'bmw', 'nein']],
      dtype=object)

In [37]:
y = base.iloc[:, 0].values
y # conteudo da variavel

array([  480, 18300,  9800, ...,  9200,  3400, 28990])

In [38]:
# volkswagen - 0
# bmw        - 1
# audi       - 2

# 1 0 0
# 0 1 0
# 0 0 1
base['brand'].value_counts()

brand
volkswagen        76755
bmw               38982
opel              38557
mercedes_benz     34498
audi              31884
ford              24761
renault           17367
peugeot           10777
fiat               9339
seat               6815
skoda              5572
mazda              5529
smart              5159
citroen            5038
nissan             4893
toyota             4616
hyundai            3585
mini               3354
sonstige_autos     3331
volvo              3229
mitsubishi         2956
honda              2726
kia                2494
suzuki             2274
alfa_romeo         2250
porsche            2154
chevrolet          1791
chrysler           1373
dacia               889
jeep                784
daihatsu            774
land_rover          759
subaru              746
jaguar              603
daewoo              530
saab                516
trabant             489
lancia              467
rover               462
lada                213
Name: count, dtype: int64

In [39]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

onehotencoder = ColumnTransformer(transformers=[("OneHot", OneHotEncoder(),
                                                 [0, 1, 3, 5, 8, 9, 10])], # Índices das colunas categóricas
                                  remainder='passthrough') # Mantém as colunas que não foram transformadas

In [40]:
X = onehotencoder.fit_transform(X).toarray()
X

array([[0.00e+00, 1.00e+00, 0.00e+00, ..., 0.00e+00, 1.50e+05, 0.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.90e+02, 1.25e+05, 5.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.63e+02, 1.25e+05, 8.00e+00],
       ...,
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.02e+02, 1.50e+05, 3.00e+00],
       [0.00e+00, 1.00e+00, 0.00e+00, ..., 1.00e+02, 1.50e+05, 6.00e+00],
       [1.00e+00, 0.00e+00, 0.00e+00, ..., 3.20e+02, 5.00e+04, 8.00e+00]])

In [41]:
base

,price,abtest,vehicleType,yearOfRegistration,gearbox,powerPS,model,kilometer,monthOfRegistration,fuelType,brand,notRepairedDamage
0,480,test,limousine,1993,manuell,0,golf,150000,0,benzin,volkswagen,nein
1,18300,test,coupe,2011,manuell,190,golf,125000,5,diesel,audi,ja
2,9800,test,suv,2004,automatik,163,grand,125000,8,diesel,jeep,nein
3,1500,test,kleinwagen,2001,manuell,75,golf,150000,6,benzin,volkswagen,nein
4,3600,test,kleinwagen,2008,manuell,69,fabia,90000,7,diesel,skoda,nein
...,...,...,...,...,...,...,...,...,...,...,...,...
371523,2200,test,limousine,2005,manuell,0,golf,20000,1,benzin,sonstige_autos,nein
371524,1199,test,cabrio,2000,automatik,101,fortwo,125000,3,benzin,smart,nein
371525,9200,test,bus,1996,manuell,102,transporter,150000,3,diesel,volkswagen,nein
371526,3400,test,kombi,2002,manuell,100,golf,150000,6,diesel,volkswagen,nein
371527,28990,control,limousine,2013,manuell,320,m_reihe,50000,8,benzin,bmw,nein

In [43]:
base.shape

(359291, 12)

In [44]:
X.shape

(359291, 316)

In [52]:
(316 + 1) / 2

158.5

In [53]:
regressor = Sequential([
    tf.keras.layers.InputLayer(shape = (316,)), # 316 colunas
    tf.keras.layers.Dense(units = 158, activation = 'relu'), # 316 + 1 / 2 = 158
    tf.keras.layers.Dense(units = 158, activation = 'relu'),
    tf.keras.layers.Dense(units = 1, activation = 'linear')
])

In [51]:
regressor.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_3 (Dense)                 │ (None, 158)            │        50,086 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 158)            │        25,122 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │           159 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 75,367 (294.40 KB)

 Trainable params: 75,367 (294.40 KB)

 Non-trainable params: 0 (0.00 B)

In [48]:
12000 - 13000, 11500 - 10000
(abs(12000 - 13000) + abs(11500 - 10000)) / 2

1250.0

In [54]:
regressor.compile(optimizer = 'adam', loss = 'mean_squared_error')
regressor.fit(X, y, batch_size = 300, epochs = 100)

Epoch 1/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 63983988.0000
Epoch 2/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 50441668.0000
Epoch 3/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 45348976.0000
Epoch 4/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 40646596.0000
Epoch 5/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 38124848.0000
Epoch 6/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 36731088.0000
Epoch 7/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 35761856.0000
Epoch 8/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 7ms/step - loss: 34908944.0000
Epoch 9/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 34467492.0000
Epoch 10/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 34010132.0000
Epoch 11/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 33667676.0000
Epoch 12/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 33265040.0000
Epoch 13/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 32876546.0000
Epoch 14/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 32713764.0000
Epoch 15/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 32292064.0000
Epoch 16/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 12s 9ms/step - loss: 32049410.0000
Epoch 17/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 31733390.0000
Epoch 18/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 31494214.0000
Epoch 19/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 31258376.0000
Epoch 20/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - loss: 31158310.0000
Epoch 21/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - loss: 31234242.0000
Epoch 22/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 30744262.0000
Epoch 23/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 30710940.0000
Epoch 24/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 30434704.0000
Epoch 25/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 30247482.0000
Epoch 26/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 30255960.0000
Epoch 27/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 29890234.0000
Epoch 28/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 30001682.0000
Epoch 29/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 29742242.0000
Epoch 30/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 29574144.0000
Epoch 31/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 29801370.0000
Epoch 32/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 29829134.0000
Epoch 33/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - loss: 29366230.0000
Epoch 34/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 29384544.0000
Epoch 35/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 29514276.0000
Epoch 36/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 8ms/step - loss: 29252642.0000
Epoch 37/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 28863248.0000
Epoch 38/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - loss: 29525818.0000
Epoch 39/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 29423216.0000
Epoch 40/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 28988364.0000
Epoch 41/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 28944292.0000
Epoch 42/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 28549576.0000
Epoch 43/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 29251756.0000
Epoch 44/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 28710914.0000
Epoch 45/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 28553210.0000
Epoch 46/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 28795228.0000
Epoch 47/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - loss: 28495978.0000
Epoch 48/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 19s 8ms/step - loss: 28495686.0000
Epoch 49/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 28349918.0000
Epoch 50/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 28615100.0000
Epoch 51/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - loss: 28033064.0000
Epoch 52/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 28567626.0000
Epoch 53/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 28450754.0000
Epoch 54/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 9ms/step - loss: 28638256.0000
Epoch 55/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 20s 8ms/step - loss: 28022884.0000
Epoch 56/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 28380944.0000
Epoch 57/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 28656376.0000
Epoch 58/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 28180974.0000
Epoch 59/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 28110112.0000
Epoch 60/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 28022146.0000
Epoch 61/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 28367292.0000
Epoch 62/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 11s 9ms/step - loss: 27971256.0000
Epoch 63/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 12s 10ms/step - loss: 27768902.0000
Epoch 64/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 28295460.0000
Epoch 65/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27804872.0000
Epoch 66/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27689740.0000
Epoch 67/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 27809836.0000
Epoch 68/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27690554.0000
Epoch 69/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 28043500.0000
Epoch 70/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 27513608.0000
Epoch 71/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27856752.0000
Epoch 72/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27295354.0000
Epoch 73/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 27867562.0000
Epoch 74/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - loss: 27839342.0000
Epoch 75/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27827522.0000
Epoch 76/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 28274506.0000
Epoch 77/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - loss: 27513190.0000
Epoch 78/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27484044.0000
Epoch 79/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 27625498.0000
Epoch 80/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 7ms/step - loss: 27527560.0000
Epoch 81/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27049724.0000
Epoch 82/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27752080.0000
Epoch 83/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 27466752.0000
Epoch 84/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27465748.0000
Epoch 85/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27653954.0000
Epoch 86/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 27289110.0000
Epoch 87/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27296474.0000
Epoch 88/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27610010.0000
Epoch 89/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 27018614.0000
Epoch 90/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27341594.0000
Epoch 91/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27375748.0000
Epoch 92/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 7ms/step - loss: 27254042.0000
Epoch 93/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 9s 8ms/step - loss: 27050268.0000
Epoch 94/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27172696.0000
Epoch 95/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 26924832.0000
Epoch 96/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27113442.0000
Epoch 97/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27143748.0000
Epoch 98/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 8s 7ms/step - loss: 27057184.0000
Epoch 99/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 27196214.0000
Epoch 100/100
1198/1198 ━━━━━━━━━━━━━━━━━━━━ 10s 8ms/step - loss: 26932084.0000

In [55]:
X.shape

(359291, 316)

In [56]:
previsoes = regressor.predict(X) # Utilizando os dados para prever

11228/11228 ━━━━━━━━━━━━━━━━━━━━ 35s 3ms/step

In [57]:
previsoes

array([[ 1038.4786],
       [ 8799.583 ],
       [10805.993 ],
       ...,
       [ 5436.7583],
       [ 2616.3765],
       [26686.29  ]], dtype=float32)

In [58]:
y

array([  480, 18300,  9800, ...,  9200,  3400, 28990])

In [59]:
y.mean()

np.float64(5916.833945186492)

In [60]:
previsoes.mean()

np.float32(5021.0757)