In [1]:
import pandas as pd
import numpy as np

In [2]:
# Níveis de Índice
outside = ['G1','G1','G1','G2','G2','G2']
inside = [1,2,3,1,2,3]
hier_index = list(zip(outside,inside))
hier_index = pd.MultiIndex.from_tuples(hier_index)

In [3]:
outside

['G1', 'G1', 'G1', 'G2', 'G2', 'G2']

In [4]:
inside

[1, 2, 3, 1, 2, 3]

In [5]:
hier_index = list(zip(outside,inside))  # Combina outside e inside em pares

In [6]:
hier_index

[('G1', 1), ('G1', 2), ('G1', 3), ('G2', 1), ('G2', 2), ('G2', 3)]

In [7]:
hier_index = pd.MultiIndex.from_tuples(hier_index) # Cria um MultiIndex a partir das tuplas

In [8]:
hier_index

MultiIndex([('G1', 1),
            ('G1', 2),
            ('G1', 3),
            ('G2', 1),
            ('G2', 2),
            ('G2', 3)],
           )

In [9]:
df = pd.DataFrame(np.random.randn(6,2), index = hier_index, columns= ['A', 'B']) # Cria DataFrame com dados aleatórios e índice hierárquico

In [10]:
df

             A         B
G1 1  0.858602 -0.033272
   2  0.048769 -1.091638
   3  0.522158 -0.406755
G2 1 -0.690492  0.651396
   2  0.833216  0.173015
   3  1.062923  1.194874

In [11]:
df.loc['G1'].loc[1] # Seleciona o nível G1 e depois o índice 1

A    0.858602
B   -0.033272
Name: 1, dtype: float64

In [12]:
df.index.names = ['Grupo', 'Numero'] # coloca o Grupo e o Numero como indice do dataframe

In [13]:
df

                     A         B
Grupo Numero
G1    1       0.858602 -0.033272
      2       0.048769 -1.091638
      3       0.522158 -0.406755
G2    1      -0.690492  0.651396
      2       0.833216  0.173015
      3       1.062923  1.194874

In [15]:
df.xs('G1') # mostra os dados que pertencem ao G1

               A         B
Numero
1       0.858602 -0.033272
2       0.048769 -1.091638
3       0.522158 -0.406755

In [16]:
df.xs(1, level='Numero')  # mostra os dados que pertencem ao numero 1

              A         B
Grupo
G1     0.858602 -0.033272
G2    -0.690492  0.651396